# Production overlay
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Reference base configuration
resources:
  - ../../base
  # Production secrets (values must be replaced before deployment)
  - secrets.yaml

# Exclude postgres resources - using managed database in production
patches:
  # Remove postgres resources
  - patch: |-
      $patch: delete
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: postgres
        namespace: taskapi
    target:
      kind: Deployment
      name: postgres

  - patch: |-
      $patch: delete
      apiVersion: v1
      kind: Service
      metadata:
        name: postgres
        namespace: taskapi
    target:
      kind: Service
      name: postgres

  - patch: |-
      $patch: delete
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: postgres-pvc
        namespace: taskapi
    target:
      kind: PersistentVolumeClaim
      name: postgres-pvc

  # Update app deployment for production
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Always
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: "500m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "512Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "2000m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "1Gi"
    target:
      kind: Deployment
      name: taskapi-app

commonLabels:
  environment: production
