# Secret for application configuration
# Contains base64-encoded JWT secret for token generation
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: taskapi
type: Opaque
data:
  # mySuperSecretKeyForJWTTokenGenerationChangeThisInProduction123456 (base64 encoded)
  JWT_SECRET: bXlTdXBlclNlY3JldEtleUZvckpXVFRva2VuR2VuZXJhdGlvbkNoYW5nZVRoaXNJblByb2R1Y3Rpb24xMjM0NTY=
