# Base Kustomization for Task API
# Environment-agnostic base configuration
# Use overlays (local, production) for environment-specific settings
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Apply resources in the specified order
resources:
  # 1. Create namespace first
  - namespace.yaml
  # 2. Create secrets (can be overridden in overlays)
  - postgres-secret.yaml
  - app-secret.yaml
  # 3. Create persistent volume claim
  - postgres-pvc.yaml
  # 4. Deploy PostgreSQL
  - postgres-deployment.yaml
  - postgres-service.yaml
  # 5. Deploy application
  - app-deployment.yaml
  - app-service.yaml
  # 6. Create ingress
  - ingress.yaml
